name: Daily KV backup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.3.0
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt -q

      - name: Export KV snapshot
        env:
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: python scripts/export_kv_snapshot.py

      - name: Upload KV snapshot
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: kv-snapshot
          path: backups
          if-no-files-found: error
          retention-days: 30
