name: Fuzzing

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          # Atheris 2.3 does not build with Python 3.12 yet
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install atheris
      - name: Run fuzzing
        run: |
          python fuzz/fuzz_notifications.py -runs=100
