name: Amul Watchdog

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 min
  workflow_dispatch:        # manual run button

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.30.0-focal
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run stock checker
        env:
          PINCODE:      ${{ secrets.PINCODE }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
        run: python check_stock.py

        # - name: Upload screenshots  # see how it improves time
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: screenshots
        #     path: artifacts
        #     retention-days: 3
