name: Amul Watchdog

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 min
  workflow_dispatch:        # manual run button

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: pw-browsers
    steps:
      - uses: actions/checkout@a5ac7e51b4109f5124bf94ecd736a1DE18960A24 # v4.1.7

      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.8.0
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Cache Playwright browsers
        uses: actions/cache@13aacd865c20de90d75decf172eb5f54f8a99820 # v4.0.2
        with:
          path: pw-browsers
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }} # Consider Playwright version in key
          restore-keys: ${{ runner.os }}-playwright-

      - name: Install deps
        run: |
          pip install --require-hashes -r requirements.txt
          playwright install chromium # This installs browsers, not python deps

      - name: Run stock checker
        env:
          PINCODE:      ${{ secrets.PINCODE }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
        run: python scripts/check_stock.py
