name: Amul Watchdog

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 min
  workflow_dispatch:        # manual run button

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: pw-browsers
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.6

      - uses: actions/setup-python@82c7e631bb3cdc8f0f68e0deca8891bf90624617 # v5.1.0
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Cache Playwright browsers
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: pw-browsers
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-playwright-

      - name: Install deps
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run stock checker
        env:
          PINCODE:      ${{ secrets.PINCODE }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
        run: python scripts/check_stock.py

        # - name: Upload screenshots  # see how it improves time
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: screenshots
        #     path: artifacts
        #     retention-days: 3
