name: Amul Watchdog

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 min
  workflow_dispatch:        # manual run button

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: pw-browsers
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Cache Playwright browsers
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3
        with:
          path: pw-browsers
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-playwright-

      - name: Install deps
        run: |
          pip install .
          playwright install chromium

      - name: Run stock checker
        env:
          PINCODE:      ${{ secrets.PINCODE }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
        run: python -m myscraper.check_stock

        # - name: Upload screenshots  # see how it improves time
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: screenshots
        #     path: artifacts
        #     retention-days: 3
